---
title: "Data cleaning experiment 4"
author: "Jan Pfänder, Hugo Mercier"
date: "2023-03-09"
output: 
  html_document: 
    keep_md: yes
---

```{r packages, message=FALSE}
library(tidyverse)     # create plots with ggplot, manipulate data, etc.
library(broom.mixed)   # convert regression models into nice tables
library(modelsummary)  # combine multiple regression models into a single table
library(lme4)          # model specification / estimation 
library(lmerTest)      # provides p-values in the output
library(ggpubr)        # stile feature of ggplot
library(gghalves)      # do special plots in ggplot
library(kableExtra)    # for tables
```

## Import data
```{r import}
d <- read_csv("./data/qualtrics.csv")
names(d)
```

```{r}
# delete first two rows
d <- d %>% 
  slice(3: nrow(.)) 
```

## Attention checks 
```{r attention}
# attention check
# to see different answers given (i.e.levels), transform into factor
d$attention <- as.factor(d$attention)
# check levels to see different answer types
levels(d$attention) 
```

No one failed the attention check. 

## Re-shape data
```{r}
d <- d %>% 
  # add an easy to read participant identifier
  mutate(id = 1:nrow(.)) %>% 
  # bring to long format
  pivot_longer(cols = c("0_acc_a_1" : "3_com_b"), 
               names_to = "condition", values_to = "score") %>% 
  # For some weird reason, qualtrics added `_1` at the end of each accuracy
  # stimulus name. We remove that
  mutate(across(condition, ~str_remove(., "_1"))) %>% 
  # separate conditions into CONVERGENCE_OUTCOME_STIMULUS
  separate_wider_delim(condition, "_", names = c("convergence", "outcome", 
                                                 "stimulus_variant")
                       ) %>%
  pivot_wider(names_from = outcome, values_from = score) %>% 
  # create better variable names
  rename(competence = com, 
         accuracy = acc) %>% 
  # all variables are coded as `character` - make key variables numeric
  mutate(across(c(convergence, competence, accuracy), as.numeric), 
         # make a categorical variable from `convergence`
         convergence_categorical = recode_factor(convergence, 
                                                 `0` = "opposing majority", 
                                                 `1` = "divergence", 
                                                 `2` = "majority", 
                                                 `3` = "consensus",
                                                 .default = NA_character_)
         )
```

## Recode demographics

```{r, message=FALSE}
prolific_demographics <- read_csv("./data/prolific_demographics.csv")

d <- left_join(d, prolific_demographics, by = c("PROLIFIC_PID" = "Participant id"))
```


```{r}
d <- d %>% 
  mutate(gender = case_when(Sex == "Male" ~ "male", 
                            Sex == "Female" ~  "female", 
                            .default = NA)
         )
```

## Export data

```{r}
write_csv(d, "data/cleaned.csv")
```